// tests/kb-curate-skill.test.ts — content/structure test for the kb-curate SKILL.md.
// This is NOT an LLM-judgment test; the real acceptance gate is a separate manual
// review of distilled-note quality (mode: hitl). This auto-gate asserts the 8
// curation rule-areas are present and correctly ordered in the skill's
// instructions, that the skill is pure markdown, and that it references the
// kb_* tools + native write/edit (NOT kb_put/kb_delete).

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const SKILL_PATH = join(__dirname, '..', 'skill', 'kb-curate', 'SKILL.md');

/** Load the raw SKILL.md text. */
function loadSkill(): string {
  return readFileSync(SKILL_PATH, 'utf-8');
}

/** Parse the YAML frontmatter (between the first two `---` lines) into a record. */
function parseFrontmatter(text: string): Record<string, string> {
  const match = text.match(/^---\n([\s\S]*?)\n---/);
  if (!match) throw new Error('No frontmatter found in SKILL.md');
  const yaml = match[1];
  const record: Record<string, string> = {};
  for (const line of yaml.split('\n')) {
    const m = line.match(/^(\w[\w-]*)\s*:\s*(.*)$/);
    if (m) record[m[1]] = m[2].trim();
  }
  return record;
}

describe('kb-curate skill: frontmatter', () => {
  const text = loadSkill();

  it('has valid frontmatter with name === kb-curate and a description', () => {
    const fm = parseFrontmatter(text);
    expect(fm.name).toBe('kb-curate');
    expect(fm.description).toBeTruthy();
    expect(fm.description!.length).toBeGreaterThan(20);
  });
});

describe('kb-curate skill: 8 rule-areas present and ordered', () => {
  const text = loadSkill();
  const lc = text.toLowerCase();

  // Helper: find the 0-based index of a phrase.
  const indexOf = (needle: string): number => lc.indexOf(needle.toLowerCase());

  it('Rule 1 — Triggers: when to curate (user says save/research into KB; durable claim) and NOT to curate (ephemeral/one-off)', () => {
    expect(indexOf('trigger')).toBeGreaterThanOrEqual(0);
    // "save this" / "research x into" / "add this to the kb"
    expect(lc).toMatch(/save.*to the kb|save.*session|research.*into the kb|add.*to the kb/);
    // durable, reusable
    expect(lc).toMatch(/durable|reusable/);
    // must NOT curate ephemeral/one-off work
    expect(lc).toMatch(/ephemeral|one.?off|do not curate.*ephemeral|not.*curate.*one.?off/);
  });

  it('Rule 2 — Type selection: all 5 types incl. generic as the gauge', () => {
    expect(indexOf('type selection')).toBeGreaterThanOrEqual(0);
    // All 5 types must be named
    expect(lc).toContain('term');
    expect(lc).toContain('concept');
    expect(lc).toContain('decision');
    expect(lc).toContain('reference');
    expect(lc).toContain('generic');
    // generic is the gauge: anything that doesn't fit the four → generic until type vocab extended
    expect(lc).toMatch(/gauge|doesn.?t fit|does not fit|until.*type.*vocab|type vocab.*extend/);
  });

  it('Rule 3 — Provenance: generated.by, sources (with author/last_modified), conflicts as separate entries', () => {
    expect(lc).toMatch(/generated\.by|generated by/);
    expect(lc).toContain('sources');
    // pi/<version>/<model>
    expect(lc).toMatch(/pi\/.*version.*model|pi\/<version>|pi\/<ver>|pi\/\d+\.\d+/);
    // sources shape: resource, title, author, last_modified
    expect(lc).toContain('resource');
    expect(lc).toContain('author');
    expect(lc).toContain('last_modified');
    // conflicting sources → separate entries, noted in the body
    expect(lc).toMatch(/conflict.*separate|separate.*source|separate.*entries/);
  });

  it('Rule 4 — Lifecycle: draft/unverified for AI notes, never self-promote, deprecate with consent', () => {
    expect(lc).toContain('draft');
    expect(lc).toContain('unverified');
    // never self-promote draft→stable
    expect(lc).toMatch(/self.?promote|never.*promote.*draft|never.*draft.*stable/);
    // deprecate only with explicit consent
    expect(lc).toMatch(/deprecat.*consent|consent.*deprecat|explicit.*consent.*deprecat/);
    // human review flips both
    expect(lc).toMatch(/human.*review.*flips|human.*flips|review.*flips/);
  });

  it('Rule 5 — Authoring model: native write/edit + kb_update + kb_check_id, NO kb_put/kb_delete', () => {
    expect(lc).toMatch(/native write|native.*write.*edit|write.*edit.*native/);
    expect(lc).toContain('kb_update');
    expect(lc).toContain('kb_check_id');
    // kb_update({ref, content}) reindex
    expect(lc).toMatch(/reindex|re.?index/);
    // kb_check_id validate/conformance
    expect(lc).toMatch(/conformance|validate|validation/);
  });

  it('Rule 6 — Link, don\'t duplicate: kb_search before creating', () => {
    expect(lc).toMatch(/link.*don.?t duplicate|link.*not.*duplicate|link.*instead of duplicat/);
    expect(lc).toContain('kb_search');
    expect(lc).toMatch(/kb_search.*before creat|search.*before creat|before creat.*search/);
    // near-match → link (typed relation + prose link) instead of duplicate
    expect(lc).toMatch(/near.?match|near match/);
    // for a wrong human note: correcting linked decision/concept note preferred; may edit but linking is default
    expect(lc).toMatch(/wrong.*human|correcting.*linked|correcting.*decision|correcting.*concept|disagreement/);
  });

  it('Rule 7 — Frontmatter shape: id type:slug, type, title, description, tags, relations, generated, sources, status draft, stale_after', () => {
    expect(lc).toContain('id');
    expect(lc).toMatch(/type:slug|type.*:.*slug/);
    expect(lc).toContain('title');
    expect(lc).toContain('description');
    expect(lc).toContain('tags');
    expect(lc).toContain('relations');
    expect(lc).toContain('status');
    expect(lc).toContain('stale_after');
  });

  it('Rule 8 — Edit-anything + git: agent may edit any note, git is the undo, append provenance on edit', () => {
    expect(lc).toMatch(/edit.*anything|may edit any|edit any note/);
    expect(lc).toMatch(/git.*undo|git.*safety|git.*backstop|undo.*git/);
    // append provenance on edit, don't erase original author's
    expect(lc).toMatch(/append.*provenance|provenance.*append|don.?t erase.*author|not.*erase.*author/);
  });

  it('the 8 rule headings appear in order (1 → 8)', () => {
    // Match the ## Rule N heading line, like kb-ask's test matches `## Step N`.
    // The headings are the canonical sequence markers; intro text may mention
    // concepts out of order (e.g. "provenance" in the description), so we use
    // the heading lines, not the first body mention.
    const headingIdx = (n: number): number => lc.indexOf(`## rule ${n}`);
    const order = [
      { name: 'triggers', idx: headingIdx(1) },
      { name: 'type-selection', idx: headingIdx(2) },
      { name: 'provenance', idx: headingIdx(3) },
      { name: 'lifecycle', idx: headingIdx(4) },
      { name: 'authoring', idx: headingIdx(5) },
      { name: 'link', idx: headingIdx(6) },
      { name: 'frontmatter', idx: headingIdx(7) },
      { name: 'edit', idx: headingIdx(8) },
    ];
    for (const s of order) {
      expect(s.idx, `${s.name} rule heading not found`).toBeGreaterThanOrEqual(0);
    }
    for (let i = 1; i < order.length; i++) {
      expect(
        order[i].idx,
        `${order[i].name} (idx ${order[i].idx}) should come after ${order[i - 1].name} (idx ${order[i - 1].idx})`,
      ).toBeGreaterThan(order[i - 1].idx);
    }
  });
});

describe('kb-curate skill: tool references', () => {
  const text = loadSkill();
  const lc = text.toLowerCase();

  it('references kb_search, kb_update, and kb_check_id (at minimum)', () => {
    expect(lc).toContain('kb_search');
    expect(lc).toContain('kb_update');
    expect(lc).toContain('kb_check_id');
  });
});

describe('kb-curate skill: remote note references kb_put / kb_delete', () => {
  const text = loadSkill();
  const lc = text.toLowerCase();

  it('references kb_put and kb_delete in the remote KB note (slice 3: when the KB is remote, author with kb_put/kb_delete)', () => {
    // Slice 3 adds a one-line note: "When the KB is remote (isRemoteKb detects a
    // non-localhost KB_URL), author with kb_put/kb_delete, not native write/edit."
    // The skill must reference kb_put/kb_delete in this remote context.
    expect(lc).toMatch(/kb_put/);
    expect(lc).toMatch(/kb_delete/);
    expect(lc).toMatch(/remote/);
    expect(lc).toMatch(/isremotekb/);
  });
});

describe('kb-curate skill: pure markdown — no code / no daemon imports', () => {
  const text = loadSkill();

  it('does NOT contain @kb/fs imports or references', () => {
    expect(text.toLowerCase()).not.toContain('@kb/fs');
    expect(text.toLowerCase()).not.toContain('import @kb/fs');
    expect(text.toLowerCase()).not.toContain("require('@kb/fs')");
  });

  it('does NOT contain daemon imports or tRPC client creation', () => {
    const lc = text.toLowerCase();
    expect(lc).not.toContain('createtrpcclient');
    expect(lc).not.toContain('createkbtrpcclient');
    expect(lc).not.toContain('httpbatchlink');
    expect(lc).not.toContain('import \'@kb/daemon');
    expect(lc).not.toContain('import \'@kb/protocol');
    expect(lc).not.toContain('import "@kb/daemon');
    expect(lc).not.toContain('import "@kb/protocol');
  });

  it('instructs the agent to call the tools by name (native write/edit + kb_* tools)', () => {
    const lc = text.toLowerCase();
    // The skill teaches calling kb_* tools by name, not building a client.
    expect(lc).toMatch(/native write|write\/edit|write.*edit.*native/);
    expect(lc).toContain('kb_search');
    expect(lc).toContain('kb_update');
    expect(lc).toContain('kb_check_id');
  });
});

describe('kb-curate skill: example note', () => {
  const text = loadSkill();
  const lc = text.toLowerCase();

  it('includes a worked example of distilling a decision-making session into a decision note', () => {
    expect(lc).toContain('example');
    // example distills a decision-making session
    expect(lc).toMatch(/decision.?making|decision.*session|session.*decision/);
    // example produces a decision note with an id like decision:slug
    expect(lc).toMatch(/decision:[a-z]|decision:/);
    // generated.by in the example
    expect(lc).toMatch(/generated\.by.*pi|pi\/.*model|pi\/\d+\.\d+/);
    // status: draft in the example
    expect(lc).toMatch(/status:?\s*draft|status.*draft/);
    // sources in the example (the session)
    expect(lc).toContain('sources');
  });

  it('example includes a relation to a backing concept note with a prose link', () => {
    // The example should show a relation (e.g. decided_in) linking the
    // decision note to a concept note it backs, with a prose markdown link.
    expect(lc).toMatch(/decided_in|relation|relations/);
    expect(lc).toMatch(/\[.*\]\(.*:.*\)|prose.*link|markdown link/);
  });
});
